name: "Setup Rust toolchain"
description: "Select the stable Rust toolchain and install required components using the runner-provided rustup."
inputs:
  toolchain:
    description: "Rust toolchain channel, version, or target triple."
    required: false
    default: "stable"
runs:
  using: "composite"
  steps:
    - name: Set default toolchain
      shell: bash
      run: rustup default "${{ inputs.toolchain }}"

    - name: Install required components
      shell: bash
      run: rustup component add --toolchain "${{ inputs.toolchain }}" rustfmt clippy

    - name: Show active toolchain
      shell: bash
      run: rustup show active-toolchain
